### PR TITLE
Update create-release.zsh- Strip binary to make 15M smaller

### PR DESCRIPTION
**Pull request by munntjlx**
I added this little change to make the image about 10mb smaller. You might want to see if stripping out the debug symbols has any negative effects on the performace etc.

### CODE REVIEW

**Comment by bradlarsen** [comment]
The downsides I can think of for stripping the binary are:

- If noseyparker were to crash with a `panic`, it could not give a useful stack trace
- Sampling profiling (e.g., `perf`) would be much less useful on a stripped binary
- Debugging would be hindered

I don't want to unconditionally strip the binaries in the releases for the above reasons.

However, stripping _does_ noticeably shrink the binary. I would enable this by default in the Alpine-based Docker image (where one of the main motivations is image size).

If you want to make the `strip` step optional via a runtime argument to `create-release.zsh`, and pass that argument in the call to `create-release.zsh` in `Dockerfile.alpine`, I will merge it back in.

**Comment by munntjlx** [comment]
I probably am not as conversant with dockerfile arguments..... I did create an additional file that has the directive in the scripts directory.

________________________________________

**Comment by bradlarsen** [comment]
@munntjlx What I had in mind was not a Dockerfile argument, but rather:

- modifying the `scripts/create-release.zsh` script to take an optional `--strip` argument that causes `strip` to be run
- modifying `Dockerfile.alpine` so that when it calls `scripts/create-release.zsh`, it passes the new `--strip` argument

This would avoid code duplication in the release scripts.

I'll merge this back in, but I'm going to tweak it first as above. Thank you for the contribution! This will help provide an option for a small Docker image. (In our internal version, that's not a priority for us, as the image includes several ML model files that increase the total application size to several hundred megabytes at present.)

**Comment by munntjlx** [comment]
I wish we could have the ML models, but you NoseyParkerItes still have to eat!

**Comment by bradlarsen** [comment]
@munntjlx I reimplemented this on `main` just now in commit 0981a40ad13fc8dac1bf89e30b62d2476702305a.

I think I made a typo in the `co-authored-by` line to list you as a contributor on that. My apologies!

**Pull request closed without merging**
