### PR TITLE
Fix build of vectorscan-sys on non-Linux platforms

### PR DESCRIPTION
**Pull request by yonas**

### CODE REVIEW

**Comment by yonas** [comment]
> What build failure error messages have you seen, and on which platforms?

@bradlarsen On FreeBSD, I got "Fat runtime is not supported on non-Intel architectures" from crates/vectorscan-sys/vectorscan/CMakeLists.txt, line 493.

**Comment by bradlarsen** [comment]
ARM FreeBSD then?

**Comment by yonas** [comment]
> ARM FreeBSD then?

amd64.

**Comment by bradlarsen** [comment]
> > ARM FreeBSD then?
> 
> amd64.

Gotcha! The error message that gets produced by the vectorscan build scripts is confusingly wrong then.

Thanks for the PR! With this change, does Nosey Parker actually build and run successfully on your FreeBSD machine? (I don't have one of those sitting around for easy testing.)

**Review by bradlarsen — COMMENTED** [review]
I'm in favor of this PR, but the particular change in the conditional here might not be quite correct.

I will have to take a closer look at the effects of this to ensure that the "fat runtime" for vectorscan still gets enabled on Linux builds. Without that enabled, it's possible that a Linux release build of Nosey Parker, when run on a different CPU microarchitecture, would fail at runtime.

**Comment by yonas** [comment]
> With this change, does Nosey Parker actually build and run successfully on your FreeBSD machine?

Yes, it builds but I'm not sure if it works properly. Running `cargo test` produces 5 errors:

```
❯ cargo test
...
warning: unused imports: `assert_cmd_snapshot`, `noseyparker_failure`, `noseyparker_success`, `noseyparker`
  --> crates/noseyparker-cli/tests/common/mod.rs:62:10
   |
62 | pub use {noseyparker, noseyparker_success, noseyparker_failure, assert_cmd_snapshot};
   |          ^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: `noseyparker-cli` (test "test_noseyparker") generated 1 warning (run `cargo fix --test "test_noseyparker"` to apply 1 suggestion)
    Finished test [unoptimized + debuginfo] target(s) in 1.00s
     Running unittests src/lib.rs (target/debug/deps/bstring_serde-a2f1d9e14ff1ad99)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/content_guesser-8eee464a24c4b106)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/input_enumerator-95ddb31b18a4db8f)

running 1 test
test bstring_table::tests::simple_roundtrip ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/noseyparker-ff9f47515c2d366b)

running 24 tests
test blob_id::test::simple ... ok
test git_url::test::bad_query_params ... ok
test git_url::test::bad_scheme_02 ... ok
test git_url::test::bad_scheme_03 ... ok
test git_url::test::bad_scheme_01 ... ok
test datastore::test::clone_destination::https_02 ... ok
test git_url::test::bad_scheme_04 ... ok
test datastore::test::clone_destination::https_01 ... ok
test git_url::test::ok_empty_path_02 ... ok
test git_url::test::ok_empty_path_01 ... ok
test git_url::test::ok_01 ... ok
test git_url::test::ok_relpath_01 ... ok
test git_url::test::ok_relpath_03 ... ok
test git_url::test::ok_relpath_02 ... ok
test github::client::test::url_from_path_parts_and_params_1 ... ok
test github::client::test::url_from_path_parts_and_params_2 ... ok
test github::client::test::url_from_path_parts_and_params_3 ... ok
test github::client::test::url_from_path_parts_and_params_4 ... ok
test github::client::test::url_from_path_parts_and_params_6 ... ok
test github::client::test::url_from_path_parts_and_params_5 ... ok
test github::client::test::url_from_path_parts_and_params_7 ... ok
test rules_database::test::test_vectorscan_sanity ... ok
test matcher::test::test_simple ... ok
test defaults::test::test_get_default_rules ... ok

test result: ok. 24 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

     Running unittests src/main.rs (target/debug/deps/noseyparker_cli-df9a2605fc806f14)

running 1 test
test test::failure - should panic ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test_noseyparker.rs (target/debug/deps/test_noseyparker-4a99db2701a685c2)

running 60 tests
test help::help_github_repos_short ... ok
test help::help_datastore ... ok
test help::help_github_short ... ok
test help::help_github ... ok
test help::help_github_repos ... ok
test help::help ... ok
test help::help_rules ... ok
test help::help_report ... ok
test help::help_report_short ... ok
test help::version_command ... ok
test help::version_long ... ok
test help::help_short ... ok
test help::help_summarize_short ... ok
test help::no_args ... ok
test help::help_summarize ... ok
test help::help_scan_short ... ok
test rules::rules_list_jsonl ... ok
test help::help_scan ... ok
test rules::rules_list_json ... ok
test rules::rules_list_noargs ... ok
test github::github_repos_list_user_jsonl_format ... ok
test github::github_repos_list_user_json_format ... ok
test github::github_repos_list_user_human_format ... ok
test github::github_repos_list_multiple_user_dedupe_jsonl_format ... ok
test rules::rules_check_builtins ... ok
test scan::basic::scan_datastore_argorder ... ok
test scan::basic::scan_emptyfile ... ok
test scan::basic::scan_emptydir ... ok
test scan::basic::scan_datastore_envvar ... ok
test scan::git_url::file_scheme ... ok
test scan::basic::report_unlimited_matches ... ok
test scan::git_url::http_scheme ... ok
test scan::basic::scan_datastore_short ... ok
test scan::basic::scan_emptyfiles ... ok
test scan::git_url::no_scheme ... ok
test scan::git_url::ssh_scheme ... ok
test scan::basic::report_output_colors1 ... ok
test scan::snippet_length::scan_invalid_snippet_length ... ok
test scan::basic::scan_file_symlink ... ok
stored new snapshot /memfs/git/noseyparker/crates/noseyparker-cli/tests/github/snapshots/test_noseyparker__github__github_repos_list_org_badtoken-3.snap.new
stored new snapshot /memfs/git/noseyparker/crates/noseyparker-cli/tests/github/snapshots/test_noseyparker__github__github_repos_list_noargs-3.snap.new
stored new snapshot /memfs/git/noseyparker/crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__summarize_nonexistent_default_datastore-3.snap.new
stored new snapshot /memfs/git/noseyparker/crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__report_nonexistent_default_datastore-3.snap.new
stored new snapshot /memfs/git/noseyparker/crates/noseyparker-cli/tests/github/snapshots/test_noseyparker__github__github_repos_list_user_badtoken-3.snap.new
test github::github_repos_list_org_badtoken ... FAILED
test github::github_repos_list_noargs ... FAILED
test github::github_repos_list_user_badtoken ... FAILED
test scan::basic::summarize_nonexistent_default_datastore ... FAILED
test scan::basic::report_nonexistent_default_datastore ... FAILED
test scan::basic::scan_git_emptyrepo ... ok
test scan::basic::scan_default_datastore ... ok
test scan::git_url::git_binary_missing ... ok
test scan::basic::scan_unreadable_file ... ok
test scan::basic::scan_secrets1 ... ok
test scan::git_url::https_nonexistent ... ok
test scan::with_ignore::glob_01 ... ok
test scan::with_ignore::literal_match_01 ... ok
test scan::with_ignore::literal_match_03 ... ok
test scan::with_ignore::negation_01 ... ok
test scan::with_ignore::literal_match_02 ... ok
test scan::with_ignore::path_glob_01 ... ok
test scan::basic::scan_file_maxsize ... ok
test scan::with_ignore::root_input_noignore_01 - should panic ... ok
test scan::with_ignore::root_input_noignore_02 - should panic ... ok
test scan::snippet_length::scan_changing_snippet_length ... ok

failures:

---- github::github_repos_list_org_badtoken stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/noseyparker-cli/tests/github/snapshots/test_noseyparker__github__github_repos_list_org_badtoken-3.snap
Snapshot: github_repos_list_org_badtoken-3
Source: crates/noseyparker-cli/tests/github/mod.rs:18
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: stderr
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    1     1 │ 
    2     2 │ Caused by:
    3     3 │     0: error making request: HTTP status client error (401 Unauthorized) for url (https://api.github.com/rate_limit)
    4     4 │     1: HTTP status client error (401 Unauthorized) for url (https://api.github.com/rate_limit)
          5 │+
          6 │+Stack backtrace:
          7 │+   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
          8 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/error.rs:551:25
          9 │+   1: <T as core::convert::Into<U>>::into
         10 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/convert/mod.rs:757:9
         11 │+   2: anyhow::kind::Trait::new
         12 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/kind.rs:93:9
         13 │+   3: noseyparker::github::enumerate_repo_urls
         14 │+             at /memfs/git/noseyparker/crates/noseyparker/src/github.rs:73:13
         15 │+   4: noseyparker_cli::cmd_github::list_repos
         16 │+             at ./src/cmd_github.rs:19:21
         17 │+   5: noseyparker_cli::cmd_github::run
         18 │+             at ./src/cmd_github.rs:11:35
         19 │+   6: noseyparker_cli::try_main
         20 │+             at ./src/main.rs:102:40
         21 │+   7: noseyparker_cli::main
         22 │+             at ./src/main.rs:112:21
         23 │+   8: core::ops::function::FnOnce::call_once
         24 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/ops/function.rs:250:5
         25 │+   9: std::sys_common::backtrace::__rust_begin_short_backtrace
         26 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/sys_common/backtrace.rs:155:18
         27 │+  10: std::rt::lang_start::{{closure}}
         28 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:167:18
         29 │+  11: std::rt::lang_start_internal
         30 │+  12: std::rt::lang_start
         31 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:166:17
         32 │+  13: main
         33 │+  14: __libc_start1
         34 │+  15: _start
         35 │+             at /usr/src/lib/csu/amd64/crt1_s.S:83
────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'github::github_repos_list_org_badtoken' panicked at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'github_repos_list_org_badtoken-3' failed in line 18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- github::github_repos_list_noargs stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/noseyparker-cli/tests/github/snapshots/test_noseyparker__github__github_repos_list_noargs-3.snap
Snapshot: github_repos_list_noargs-3
Source: crates/noseyparker-cli/tests/github/mod.rs:8
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: stderr
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    0     0 │ Error: No repositories specified
          1 │+
          2 │+Stack backtrace:
          3 │+   0: anyhow::error::<impl anyhow::Error>::msg
          4 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/error.rs:83:36
          5 │+   1: anyhow::__private::format_err
          6 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/lib.rs:675:13
          7 │+   2: noseyparker_cli::cmd_github::list_repos
          8 │+             at ./src/cmd_github.rs:17:9
          9 │+   3: noseyparker_cli::cmd_github::run
         10 │+             at ./src/cmd_github.rs:11:35
         11 │+   4: noseyparker_cli::try_main
         12 │+             at ./src/main.rs:102:40
         13 │+   5: noseyparker_cli::main
         14 │+             at ./src/main.rs:112:21
         15 │+   6: core::ops::function::FnOnce::call_once
         16 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/ops/function.rs:250:5
         17 │+   7: std::sys_common::backtrace::__rust_begin_short_backtrace
         18 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/sys_common/backtrace.rs:155:18
         19 │+   8: std::rt::lang_start::{{closure}}
         20 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:167:18
         21 │+   9: std::rt::lang_start_internal
         22 │+  10: std::rt::lang_start
         23 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:166:17
         24 │+  11: main
         25 │+  12: __libc_start1
         26 │+  13: _start
         27 │+             at /usr/src/lib/csu/amd64/crt1_s.S:83
────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'github::github_repos_list_noargs' panicked at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'github_repos_list_noargs-3' failed in line 8

---- github::github_repos_list_user_badtoken stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/noseyparker-cli/tests/github/snapshots/test_noseyparker__github__github_repos_list_user_badtoken-3.snap
Snapshot: github_repos_list_user_badtoken-3
Source: crates/noseyparker-cli/tests/github/mod.rs:28
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: stderr
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    1     1 │ 
    2     2 │ Caused by:
    3     3 │     0: error making request: HTTP status client error (401 Unauthorized) for url (https://api.github.com/rate_limit)
    4     4 │     1: HTTP status client error (401 Unauthorized) for url (https://api.github.com/rate_limit)
          5 │+
          6 │+Stack backtrace:
          7 │+   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
          8 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/error.rs:551:25
          9 │+   1: <T as core::convert::Into<U>>::into
         10 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/convert/mod.rs:757:9
         11 │+   2: anyhow::kind::Trait::new
         12 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/kind.rs:93:9
         13 │+   3: noseyparker::github::enumerate_repo_urls
         14 │+             at /memfs/git/noseyparker/crates/noseyparker/src/github.rs:73:13
         15 │+   4: noseyparker_cli::cmd_github::list_repos
         16 │+             at ./src/cmd_github.rs:19:21
         17 │+   5: noseyparker_cli::cmd_github::run
         18 │+             at ./src/cmd_github.rs:11:35
         19 │+   6: noseyparker_cli::try_main
         20 │+             at ./src/main.rs:102:40
         21 │+   7: noseyparker_cli::main
         22 │+             at ./src/main.rs:112:21
         23 │+   8: core::ops::function::FnOnce::call_once
         24 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/ops/function.rs:250:5
         25 │+   9: std::sys_common::backtrace::__rust_begin_short_backtrace
         26 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/sys_common/backtrace.rs:155:18
         27 │+  10: std::rt::lang_start::{{closure}}
         28 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:167:18
         29 │+  11: std::rt::lang_start_internal
         30 │+  12: std::rt::lang_start
         31 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:166:17
         32 │+  13: main
         33 │+  14: __libc_start1
         34 │+  15: _start
         35 │+             at /usr/src/lib/csu/amd64/crt1_s.S:83
────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'github::github_repos_list_user_badtoken' panicked at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'github_repos_list_user_badtoken-3' failed in line 28

---- scan::basic::summarize_nonexistent_default_datastore stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__summarize_nonexistent_default_datastore-3.snap
Snapshot: summarize_nonexistent_default_datastore-3
Source: crates/noseyparker-cli/tests/scan/basic/mod.rs:208
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: stderr
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    2     2 │ Caused by:
    3     3 │     0: Failed to open database at datastore.np/datastore.db
    4     4 │     1: unable to open database file: datastore.np/datastore.db
    5     5 │     2: Error code 14: Unable to open the database file
          6 │+
          7 │+Stack backtrace:
          8 │+   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
          9 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/error.rs:551:25
         10 │+   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
         11 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/result.rs:1959:27
         12 │+   2: noseyparker::datastore::Datastore::new_connection
         13 │+             at /memfs/git/noseyparker/crates/noseyparker/src/datastore.rs:764:20
         14 │+   3: noseyparker::datastore::Datastore::open
         15 │+             at /memfs/git/noseyparker/crates/noseyparker/src/datastore.rs:61:20
         16 │+   4: noseyparker_cli::cmd_summarize::run
         17 │+             at /memfs/git/noseyparker/crates/noseyparker-cli/src/cmd_summarize.rs:50:21
         18 │+   5: noseyparker_cli::try_main
         19 │+             at /memfs/git/noseyparker/crates/noseyparker-cli/src/main.rs:105:43
         20 │+   6: noseyparker_cli::main
         21 │+             at /memfs/git/noseyparker/crates/noseyparker-cli/src/main.rs:112:21
         22 │+   7: core::ops::function::FnOnce::call_once
         23 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/ops/function.rs:250:5
         24 │+   8: std::sys_common::backtrace::__rust_begin_short_backtrace
         25 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/sys_common/backtrace.rs:155:18
         26 │+   9: std::rt::lang_start::{{closure}}
         27 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:167:18
         28 │+  10: std::rt::lang_start_internal
         29 │+  11: std::rt::lang_start
         30 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:166:17
         31 │+  12: main
         32 │+  13: __libc_start1
         33 │+  14: _start
         34 │+             at /usr/src/lib/csu/amd64/crt1_s.S:83
────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'scan::basic::summarize_nonexistent_default_datastore' panicked at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'summarize_nonexistent_default_datastore-3' failed in line 208

---- scan::basic::report_nonexistent_default_datastore stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/noseyparker-cli/tests/scan/basic/snapshots/test_noseyparker__scan__basic__report_nonexistent_default_datastore-3.snap
Snapshot: report_nonexistent_default_datastore-3
Source: crates/noseyparker-cli/tests/scan/basic/mod.rs:222
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expression: stderr
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    2     2 │ Caused by:
    3     3 │     0: Failed to open database at datastore.np/datastore.db
    4     4 │     1: unable to open database file: datastore.np/datastore.db
    5     5 │     2: Error code 14: Unable to open the database file
          6 │+
          7 │+Stack backtrace:
          8 │+   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
          9 │+             at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/error.rs:551:25
         10 │+   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
         11 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/result.rs:1959:27
         12 │+   2: noseyparker::datastore::Datastore::new_connection
         13 │+             at /memfs/git/noseyparker/crates/noseyparker/src/datastore.rs:764:20
         14 │+   3: noseyparker::datastore::Datastore::open
         15 │+             at /memfs/git/noseyparker/crates/noseyparker/src/datastore.rs:61:20
         16 │+   4: noseyparker_cli::cmd_report::run
         17 │+             at /memfs/git/noseyparker/crates/noseyparker-cli/src/cmd_report.rs:26:21
         18 │+   5: noseyparker_cli::try_main
         19 │+             at /memfs/git/noseyparker/crates/noseyparker-cli/src/main.rs:106:40
         20 │+   6: noseyparker_cli::main
         21 │+             at /memfs/git/noseyparker/crates/noseyparker-cli/src/main.rs:112:21
         22 │+   7: core::ops::function::FnOnce::call_once
         23 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/core/src/ops/function.rs:250:5
         24 │+   8: std::sys_common::backtrace::__rust_begin_short_backtrace
         25 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/sys_common/backtrace.rs:155:18
         26 │+   9: std::rt::lang_start::{{closure}}
         27 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:167:18
         28 │+  10: std::rt::lang_start_internal
         29 │+  11: std::rt::lang_start
         30 │+             at /wrkdirs/usr/ports/lang/rust-nightly/work/rustc-nightly-src/library/std/src/rt.rs:166:17
         31 │+  12: main
         32 │+  13: __libc_start1
         33 │+  14: _start
         34 │+             at /usr/src/lib/csu/amd64/crt1_s.S:83
────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'scan::basic::report_nonexistent_default_datastore' panicked at /home/yonas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/insta-1.34.0/src/runtime.rs:563:9:
snapshot assertion for 'report_nonexistent_default_datastore-3' failed in line 222


failures:
    github::github_repos_list_noargs
    github::github_repos_list_org_badtoken
    github::github_repos_list_user_badtoken
    scan::basic::report_nonexistent_default_datastore
    scan::basic::summarize_nonexistent_default_datastore

test result: FAILED. 55 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 17.63s

error: test failed, to rerun pass `-p noseyparker-cli --test test_noseyparker`
```

Rust: `v1.76.0-nightly`

**Comment by bradlarsen** [comment]
Interesting. There are a bunch of integration tests for Nosey Parker that rely on [Insta](https://insta.rs) for "golden" testing, where the expected output is recorded, and then test run output is compared against that, and any differences are reported as failures. (It's not ideal, but is a very effective way to quickly put together some tests that identify when behavior changes.)

The test failures I see in your output above are all from these sort of integration tests, and it looks like the output differs only by the include of stack traces, which are not in the expected output. Do you have `RUST_BACKTRACE` or some similar variable set in your environment?

Anyway, I think those test failures you are seeing are benign, and Nosey Parker is likely working for you.

**Comment by yonas** [comment]
> Do you have `RUST_BACKTRACE` or some similar variable set in your environment?

No.

> Anyway, I think those test failures you are seeing are benign, and Nosey Parker is likely working for you.

Thanks, I agree.

> I will have to take a closer look at the effects of this to ensure that the "fat runtime" for vectorscan still gets enabled on Linux builds. 

Very good :+1:

**Comment by bradlarsen** [comment]
@yonas I believe I've fixed the build failure you were seeing by eliminating Vectorscan's fat runtime entirely (a different fix than what you propose here) in #139.

Please let me know if you still have trouble with the latest from `main`!

**Comment by yonas** [comment]
@bradlarsen Works for me, thanks!

**Comment by bradlarsen** [comment]
Thanks for the PR!

**Pull request closed without merging**
